const {test}=require('node:test');
const assert=require('node:assert/strict');
const {spawn}=require('node:child_process');
const {once}=require('node:events');
const {randomUUID}=require('node:crypto');
const WebSocket=require('ws');

test('authoritative seating, moderator permissions, removal and recording lifecycle',async t=>{
  const password=randomUUID(),child=spawn(process.execPath,['server.js'],{cwd:require('node:path').join(__dirname,'..'),env:{...process.env,PORT:'0',ADMIN_PASSWORD:password,SUPABASE_URL:'',SUPABASE_SECRET_KEY:''}});
  t.after(()=>child.kill());
  const port=await new Promise((resolve,reject)=>{child.stdout.on('data',b=>{const m=String(b).match(/porta (\d+)/);if(m)resolve(m[1]);});child.on('error',reject);});
  const clients=[];t.after(()=>clients.forEach(c=>c.ws.terminate()));
  async function connect(id,listener=false,room='studio'){
    const ws=new WebSocket(`ws://localhost:${port}`),messages=[];
    ws.on('message',raw=>messages.push(JSON.parse(raw)));
    await once(ws,'open');
    const c={ws,messages,send:m=>ws.send(JSON.stringify(m)),async next(type){
      const until=Date.now()+3000;while(Date.now()<until){const i=messages.findIndex(m=>m.type===type);if(i>=0)return messages.splice(i,1)[0];await new Promise(r=>setTimeout(r,10));}throw new Error('Missing '+type);
    }};clients.push(c);c.send({type:'join',id,name:id,listener,room,seat:7,isAdmin:true});return c;
  }
  const admin=await connect('admin'),first=await admin.next('room_state');
  assert.equal(first.self.seat,0);assert.equal(first.self.isAdmin,false);assert.equal(first.self.moved,true);assert.equal(first.self.wx,.175);assert.equal(first.self.wy,.35);
  admin.send({type:'sit',seat:0});await admin.next('seat_state');
  const b=await connect('guest');assert.equal((await b.next('room_state')).self.seat,1);b.send({type:'sit',seat:1});await b.next('seat_state');
  b.send({type:'admin_action',action:'mute',target:'admin'});await b.next('admin_error');
  b.send({type:'cloud_request',requestId:'forbidden',action:'list'});assert.match((await b.next('cloud_result')).error,/administrador/);
  b.send({type:'recording_start'});await b.next('admin_error');
  admin.send({type:'admin_login',password:'wrong'});await admin.next('admin_error');
  admin.send({type:'admin_login',password});await admin.next('admin_authenticated');
  // A room transition preserves identity and isolates chat and WebRTC signaling.
  admin.send({type:'change_room',room:'backstage'});await admin.next('admin_error');
  admin.send({type:'move',space:'normalized',wx:.175,wy:.35});
  admin.send({type:'change_room',room:'backstage'});
  const backstage=await admin.next('room_state');assert.equal(backstage.room,'backstage');assert.equal(backstage.self.name,'admin');assert.equal(backstage.self.isAdmin,true);assert.equal(backstage.players.length,0);
  await b.next('leave');b.messages.length=0;
  admin.send({type:'chat',text:'private backstage'});admin.send({type:'offer',to:'guest',sdp:'private'});
  await new Promise(r=>setTimeout(r,60));assert.equal(b.messages.some(m=>m.type==='chat'||m.type==='offer'),false);
  admin.send({type:'recording_start'});await admin.next('admin_error');
  admin.send({type:'change_room',room:'garden'});await admin.next('admin_error');
  admin.send({type:'move',space:'normalized',wx:.825,wy:.35});
  admin.send({type:'change_room',room:'garden'});
  const garden=await admin.next('room_state');assert.equal(garden.room,'garden');assert.equal(garden.self.id,'admin');assert.equal(garden.self.wx,.175);assert.equal(garden.players.length,0);
  const g=require('../garden'),helper=await connect('garden-helper',false,'garden');await helper.next('room_state');
  async function walk(client,id,start,end){let p=start;for(const waypoint of g.route(start,end)){while(g.distance(p,waypoint)>1){const d=g.distance(p,waypoint),f=Math.min(1,5/d);client.messages.length=0;client.send({type:'move',space:'normalized',wx:p.x+(waypoint.x-p.x)*f,wy:p.y+(waypoint.y-p.y)*f});let m;do{m=await client.next('move');}while(m.from!==id);p={x:m.wx,y:m.wy};}}return p;}
  await walk(admin,'admin',{x:.175,y:.35},{x:.3,y:.52});
  admin.send({type:'garden_object',action:'take',id:'ball'});await new Promise(r=>setTimeout(r,30));
  await walk(helper,'garden-helper',{x:.175,y:.35},{x:.3,y:.52});
  helper.send({type:'garden_object',action:'take',id:'ball'});await helper.next('admin_error');
  admin.send({type:'garden_object',action:'drop'});await new Promise(r=>setTimeout(r,30));
  helper.messages.length=0;helper.send({type:'garden_object',action:'take',id:'ball'});assert.deepEqual((await helper.next('garden_state')).objects[0].holders,['garden-helper']);
  helper.ws.close();await new Promise(r=>setTimeout(r,30));
  let cartPosition=await walk(admin,'admin',{x:.3,y:.52},{x:.77,y:.60});
  admin.messages.length=0;admin.send({type:'garden_object',action:'take',id:'cart'});await admin.next('garden_state');
  admin.messages.length=0;admin.send({type:'move',space:'normalized',wx:cartPosition.x+.003,wy:cartPosition.y});
  assert.equal((await admin.next('move')).wx,cartPosition.x);
  const coop=await connect('cooperator',false,'garden');await coop.next('room_state');
  const helperPosition=await walk(coop,'cooperator',{x:.175,y:.35},{x:.78,y:.62});
  coop.messages.length=0;coop.send({type:'garden_object',action:'take',id:'cart'});assert.equal((await coop.next('garden_state')).objects[2].holders.length,2);
  admin.messages.length=0;coop.messages.length=0;admin.send({type:'move',space:'normalized',wx:cartPosition.x+.003,wy:cartPosition.y});
  let own;do{own=await admin.next('move');}while(own.from!=='admin');assert.ok(own.wx>cartPosition.x);cartPosition={x:own.wx,y:own.wy};
  let shared;do{shared=await coop.next('move');}while(shared.from!=='cooperator');assert.ok(shared.wx>helperPosition.x);
  coop.ws.close();await new Promise(r=>setTimeout(r,30));
  admin.messages.length=0;admin.send({type:'move',space:'normalized',wx:cartPosition.x+.003,wy:cartPosition.y});assert.equal((await admin.next('move')).wx,cartPosition.x);
  admin.send({type:'garden_object',action:'drop'});await new Promise(r=>setTimeout(r,30));
  await walk(admin,'admin',cartPosition,{x:.175,y:.35});
  admin.send({type:'change_room',room:'studio'});await admin.next('admin_error');
  admin.send({type:'recording_start'});await admin.next('admin_error');
  admin.send({type:'chat',text:'private garden'});admin.send({type:'offer',to:'guest',sdp:'private garden'});
  await new Promise(r=>setTimeout(r,60));assert.equal(b.messages.some(m=>m.type==='chat'||m.type==='offer'),false);
  admin.send({type:'change_room',room:'backstage'});
  const backFromGarden=await admin.next('room_state');assert.equal(backFromGarden.room,'backstage');assert.equal(backFromGarden.self.wx,.825);
  admin.send({type:'move',space:'normalized',wx:.175,wy:.35});
  admin.send({type:'change_room',room:'studio'});
  const returned=await admin.next('room_state');assert.equal(returned.room,'studio');assert.equal(returned.self.id,'admin');assert.equal(returned.players[0].id,'guest');
  admin.send({type:'sit',seat:0});await admin.next('seat_state');
  await b.next('seat_state');
  admin.send({type:'admin_action',action:'mute',target:'guest'});assert.equal((await b.next('participant_moderation')).adminMuted,true);
  admin.send({type:'admin_action',action:'unmute',target:'guest'});assert.equal((await b.next('participant_moderation')).adminMuted,false);
  b.send({type:'move',wx:99999,wy:-5000});
  const listener=await connect('listener',true),snapshot=await listener.next('room_state');
  assert.equal(snapshot.self.seat,null);assert.equal(snapshot.players.find(p=>p.id==='guest').seat,1);assert.equal(snapshot.players.find(p=>p.id==='guest').wx,.175);
  b.send({type:'move',space:'normalized',wx:.7,wy:.6});
  const moved=await listener.next('move');assert.equal(moved.wx,.7);assert.equal(moved.wy,.6);assert.equal(moved.from,'guest');
  b.send({type:'move',space:'normalized',wx:8,wy:-5});
  const bounded=await listener.next('move');assert.equal(bounded.wx,.9);assert.equal(bounded.wy,.32);
  listener.send({type:'move',space:'normalized',wx:.4,wy:.5});
  b.send({type:'chat',from:'admin',text:'hello'});assert.equal((await admin.next('chat')).from,'guest');
  admin.send({type:'recording_start',mode:'video'});assert.equal((await listener.next('recording_state')).recording.mode,'video');
  b.send({type:'recording_stop'});await b.next('admin_error');
  b.send({type:'sit',seat:0});await b.next('admin_error');
  b.send({type:'sit',seat:1});assert.equal((await b.next('seat_state')).moved,false);
  b.send({type:'stand'});assert.equal((await b.next('seat_state')).moved,true);
  b.send({type:'sit',seat:1});await b.next('seat_state');
  b.send({type:'hand_raise',raised:true});assert.ok((await b.next('hand_state')).handRaisedAt);
  admin.send({type:'admin_action',action:'mute_all'});assert.equal((await b.next('participant_moderation')).adminMuted,true);
  admin.send({type:'admin_action',action:'approve',target:'guest'});assert.equal((await b.next('hand_state')).handRaisedAt,null);assert.equal((await b.next('participant_moderation')).adminMuted,false);
  const late=await connect('late');const lateState=await late.next('room_state');assert.equal(lateState.recording.by,'admin');assert.equal(lateState.self.seat,2);assert.equal(lateState.players.find(p=>p.id==='guest').wx,.31);assert.equal(lateState.players.find(p=>p.id==='guest').moved,false);assert.equal(lateState.players.find(p=>p.id==='listener').moved,false);
  late.send({type:'sit',seat:2});await late.next('seat_state');
  for(let n=3;n<8;n++){const c=await connect('seat'+n);assert.equal((await c.next('room_state')).self.seat,n);c.send({type:'sit',seat:n});await c.next('seat_state');}
  const full=await connect('full');await full.next('room_full');
  admin.send({type:'admin_action',action:'remove',target:'guest'});await b.next('removed');
  const removed=await connect('guest');await removed.next('removed');
  const replacement=await connect('replacement');assert.equal((await replacement.next('room_state')).self.seat,1);
  // Remaining occupants keep their seat; disconnecting the recorder clears the notice.
  admin.ws.close();assert.equal((await listener.next('recording_state')).recording,null);
  const fresh=await connect('fresh',true);assert.equal((await fresh.next('room_state')).players.find(p=>p.id==='late').seat,2);
});
